const textStyles = {
  displayLarge: {
    fontFamily: "Vazir",
    fontSize: 64,
    letterSpacing: 0,
    lineHeight: 128,
    fontWeight: "900",
  },
  displayMedium: {
    fontFamily: "Vazir",
    fontSize: 56,
    letterSpacing: 0,
    lineHeight: 102,
    fontWeight: "900",
  },
  displaySmall: {
    fontFamily: "Vazir",
    fontSize: 48,
    letterSpacing: 0,
    lineHeight: 80,
    fontWeight: "900",
  },
  headlineXLarge: {
    fontFamily: "Vazir",
    fontSize: 48,
    letterSpacing: 0,
    lineHeight: 68,
    fontWeight: "700",
  },
  headlineMedium: {
    fontFamily: "Vazir",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 40,
    fontWeight: "700",
  },
  headlineSmall: {
    fontFamily: "Vazir",
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 32,
    fontWeight: "700",
  },
  headlineXSmall: {
    fontFamily: "Vazir",
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 28,
    fontWeight: "700",
  },
  bodyLarge: {
    fontFamily: "Vazir",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 22,
    fontWeight: "400",
  },
  bodyMedium: {
    fontFamily: "Vazir",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20,
    fontWeight: "400",
  },
  bodySmall: {
    fontFamily: "Vazir",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 18,
    fontWeight: "400",
  },
  boldBodyLarge: {
    fontFamily: "Vazir",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 22,
    fontWeight: "700",
  },

  boldBodyMedium: {
    fontFamily: "Vazir",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20,
    fontWeight: "700",
  },
  boldBodySmall: {
    fontFamily: "Vazir",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 18,
    fontWeight: "700",
  },

  buttonLarge: {
    fontFamily: "Vazir",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 20,
    fontWeight: "500",
  },
  buttonMedium: {
    fontFamily: "Vazir",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 16,
    fontWeight: "500",
  },
  buttonSmall: {
    fontFamily: "Vazir",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 14,
    fontWeight: "500",
  },
  paragraphLarge: {
    fontFamily: "Vazir",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 32,
    fontWeight: "400",
  },
  paragraphMedium: {
    fontFamily: "Vazir",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 28,
    fontWeight: "400",
  },
  paragraphSmall: {
    fontFamily: "Vazir",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 24,
    fontWeight: "400",
  },
  captionLarge: {
    fontFamily: "Vazir",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 20,
    fontWeight: "400",
  },
  captionMedium: {
    fontFamily: "Vazir",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 18,
    fontWeight: "400",
  },
  captionSmall: {
    fontFamily: "Vazir",
    fontSize: 10,
    letterSpacing: 0,
    lineHeight: 18,
    fontWeight: "400",
  },
};

export default textStyles;
